// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4mu3uWb2e1F3Bqb1ypVsT_NwnUqJnBbw',
    appId: '1:685703390929:android:429f36049eaf20afb587f0',
    messagingSenderId: '685703390929',
    projectId: 'e-com-flutter-fef78',
    databaseURL: 'https://e-com-flutter-fef78-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-com-flutter-fef78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjc129pk2xcc8udW2L0bROeGBP9AICZKQ',
    appId: '1:685703390929:ios:4ccc1b2698744014b587f0',
    messagingSenderId: '685703390929',
    projectId: 'e-com-flutter-fef78',
    databaseURL: 'https://e-com-flutter-fef78-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-com-flutter-fef78.firebasestorage.app',
    iosBundleId: 'com.example.demologinfirebase',
  );
}
